# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb777035a5b42a698c53d509643126c5"
organization_id = "129348354"
name = "shop-chat-agent"
application_url = "https://shop-chat-agent-whatsapp-j6ftf.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://shop-chat-agent-whatsapp-j6ftf.ondigitalocean.app/api/auth" ]

[customer_authentication]
redirect_uris = [
  "https://shop-chat-agent-whatsapp-j6ftf.ondigitalocean.app/auth/callback"
]